name: Build and Run bolt.diy

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '20.15.1' # Sesuaikan dengan versi Node yang dibutuhkan
        cache: 'pnpm'

    - name: Install pnpm
      uses: pnpm/action-setup@v2
      with:
        version: 9.4.0

    - name: Install dependencies
      run: pnpm install

    - name: Build project
      run: pnpm build

    - name: Run application
      run: |
        pnpm start &
        sleep 10 # Tunggu aplikasi startup
        curl http://localhost:3000 # Sesuaikan port dengan aplikasi Anda
