name: Run

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  dev:
    name: Development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup and Build
        uses: ./.github/actions/setup-and-build

      - name: Run development server
        run: pnpm run dev
