name: Run

on:
  push:

jobs:
  dev:
    name: Development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Expose with Ngrok
        uses: https://github.com/marketplace/actions/github-action-for-ngrok
        with:
          auth-token: ${{ secrets.NGROK_AUTH_TOKEN }}
          region: ap # Sesuaikan region (us, eu, ap, au)

      - name: Setup and Build
        uses: ./.github/actions/setup-and-build

      - name: Run development server
        run: pnpm run dev &
             ngrok http 3000 > /dev/null &
             sleep 5
             curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url' > url.txt
          
   
