name: Public Dev Server

on: workflow_dispatch

jobs:
  expose:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup and Build
        uses: ./.github/actions/setup-and-build
        
      - name: Verify port availability
        run: |
          if nc -z localhost 3000; then
            echo "Port 3000 is already in use"
            exit 1
          fi
      
      - name: Start development server
        run: |
          nohup pnpm run dev > server.log 2>&1 &
          echo $! > server.pid
          # Wait until server is ready
          timeout 60 bash -c 'until curl -s http://localhost:3000 >/dev/null; do sleep 1; echo "Waiting for server..."; done'
          cat server.log
      
      - name: Install Ngrok
        run: |
          curl -s https://ngrok-agent.s3.amazonaws.com/ngrok.asc | sudo tee /etc/apt/trusted.gpg.d/ngrok.asc >/dev/null
          echo "deb https://ngrok-agent.s3.amazonaws.com buster main" | sudo tee /etc/apt/sources.list.d/ngrok.list
          sudo apt update && sudo apt install ngrok
      
      - name: Authenticate Ngrok
        run: ngrok authtoken ${{ secrets.NGROK_AUTH_TOKEN }}
      
      - name: Create Ngrok tunnel
        run: |
          ngrok http 3000 > /dev/null &
          sleep 5
          curl -s http://localhost:4040/api/tunnels | jq -r '.tunnels[0].public_url' > url.txt
          echo "Public URL: $(cat url.txt)"
      
      - name: Set output
        id: ngrok-url
        run: echo "url=$(cat url.txt)" >> $GITHUB_OUTPUT
      
      - name: Display public URL
        run: echo "Your app is available at ${{ steps.ngrok-url.outputs.url }}"
      
      - name: Keep alive (60 minutes max)
        run: |
          for i in {1..60}; do
            sleep 60
            echo "Keeping alive... $i minutes passed"
          done
      
      - name: Cleanup processes
        if: always()
        run: |
          kill $(cat server.pid) 2>/dev/null || true
          pkill ngrok 2>/dev/null || true
