name: Build and Run bolt.diy

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: '1.21' # Sesuaikan dengan versi Go yang dibutuhkan

    - name: Build
      run: go build -v ./...

    - name: Run tests (optional)
      run: go test -v ./...

    - name: Run application
      run: |
        ./bolt.diy & # Menjalankan aplikasi di background
        sleep 5 # Memberi waktu untuk aplikasi startup
        curl http://localhost:8080 # Contoh pengecekan endpoint (sesuaikan portnya)
